const pi =3.14;
console.log(pi);
const name = "kankana";
let age = 20;
var course = "bsc in data science";
console.log (name);
console.log(age);
console.log(course);
let firstname="kankana";
lastname="devi";
console.log(firstname+" "+lastname);
age = 20;
nextyearage=age+1;
console.log(nextyearage);
length=10;
breadth=5;
area=length*breadth;
console.log(area);
length=10;
breadth=2;
perimeter=2*(length+breadth);
console.log(perimeter);
celcius=32;
farenheit=celcius*9/5+32;
console.log(farenheit);
principal=5000;
rate=5;
time=2;
interset=(principal*rate*time/100);
console.log(interset);
maths=95;
science=80;
english=75;
totalmarks=(maths+science+english);
percentage=(totalmarks/3);
console.log(totalmarks);
console.log(percentage);
a=10;
b=20;
c=10;
average=(a+b+c/3);
console.log(average);
Birthyear=2005;
currentyear=2026;
currentage=(currentyear-Birthyear);
console.log(currentage);



